#!/bin/bash

source ~/.bashrc
source activate wmh

### ssn ens
python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=ssn_ens --model_name=ssn_ens0_cv0  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=ssn_ens --model_name=ssn_ens0_cv1  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=ssn_ens --model_name=ssn_ens0_cv2  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=ssn_ens --model_name=ssn_ens0_cv3  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=ssn_ens --model_name=ssn_ens0_cv4  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=ssn_ens --model_name=ssn_ens0_cv5  --dataset=Ed_CVD

### punet
python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=punet --model_name=punet_cv0  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=punet --model_name=punet_cv1  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=punet --model_name=punet_cv2  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=punet --model_name=punet_cv3  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=punet --model_name=punet_cv4  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=punet --model_name=punet_cv5  --dataset=Ed_CVD

### deterministic
python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=deterministic --model_name=ens0_cv0  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=deterministic --model_name=ens0_cv1  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=deterministic --model_name=ens0_cv2  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=deterministic --model_name=ens0_cv3  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=deterministic --model_name=ens0_cv4  --dataset=Ed_CVD

python ../../evaluation/new_scripts/run_model_evaluations.py --repo_dir=/home/s2208943/ipdis/WMH_UQ_assessment --result_dir=/home/s2208943/ipdis/data/preprocessed_data/EdData_output_maps --ckpt_dir=/home/s2208943/ipdis/results/journal_models/cross_validated_models --script_loc=trustworthai/journal_run/new_MIA_fazekas_and_QC/generate_sample_diversity_and_metric_features/saving_samplediv_and_metrics.py --eval_split=test --uncertainty_type=deterministic --model_name=ens0_cv5  --dataset=Ed_CVD